language: go

go:
  - 1.13.x

matrix:
  include:
    - os: linux
      before_install:
        - sudo apt-get -y install libwebkit2gtk-4.0-dev libgtk-3-dev
      before_script:
        - diff -u <(echo -n) <(gofmt -d .)
      env: 
      - OS=linux
      - APP_NAME=Pointage_linux
    - os: osx
      before_install:
        - go get github.com/machinebox/appify
      after_success:
        - appify -name "Pointage" $APP_NAME
        - export APP_NAME=Pointage_osx.app
      osx_image: xcode8.3
      env: 
        - OS=osx
        - APP_NAME=Pointage_osx
    - os: windows
      env: 
        - OS=windows
        - APP_NAME=Pointage_win.exe

install:
  - go get -t -v ./...

script:
  - go vet $(go list ./... | grep -v /vendor/)
  - go test -v -race ./...
  - go build -o "$APP_NAME" -ldflags "-X main.Rev=`git rev-parse --short HEAD`"

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    # Your *encrypted* GitHub key, as the output of the Travis CI CLI tool.
    secure: "GkYSOZ6vGaCplSvVAsTUaXI6+s8eiyZguLomNshvdktaajkcfXpw9r+v/1B64FCz7a1pqKXlwKd8YeHoldHvho5etVpGRZXM7dEjwzQ5QIQP3DvEsmtfKW6tse4YV7DXvN2763qWaJTGDau3w1RcD6wKp4GNImUFXt6hbU+VsHolLb/Q2OZXS+lBqwRvqsQKvwZpbQYyyMiHsLCeHmkIxgMcBXmPn1b7I8H2IuGFSFTKjXR+EcoHKPUeMJuQdZByLeIeVGadpJcz+PifznSEV1jk2/mJtyMOL2IiLw+cgq+QHeCPzp9hvhcAljrWIK5z+t4ZXtZAiee8cgaCjMIfvjLajbdHx14ggROcNoEh+ensHqH+OXVd2KNK2JXTpEK9kIUiLy0rkh/JPx7LBXwhw8zslAdiOFyYgcSR9F6obva93WWZIQLM//5dFCs34bfHWOp6CGqpjSNycW9KruXV88r/DwNFJSwTChEAPMPt2vQrBCn7ODkAVB331lu2CO7lCPW8gZuFZzNVVJwfLPl4SHyhlJMITc+6pFQTMNle4mp/srMHi+cDpG1BD7FXEUZ+m9DRtqD5JWBoHqYnLYTalPT88FU+uarqiZmhK0iOAQhl8NuW8CW9ZGF1/gPOMKSapJv5VWphAnq+vNir5SUnYfOry3sy0WwgXv4RCL2W038="
  file:
  - $APP_NAME
  on:
    # Only build binaries for tagged commits
    tags: true